# Generated by Django 3.1.2 on 2021-02-06 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0002_auto_20210206_0611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guideprofile',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='avatar'),
        ),
    ]
